### ISSUE TITLE
logo purpose 

### ISSUE THREAD

**Issue by abdulmalikkhan655** [amit-bhandari/AB-Remote-Wallpaper-Changer#3]
hello,  @amit-bhandari i  want to designed a new logo for "AB-Remote-Wallpaper-Changer" and it's free.
 if you give  me permission i will send you  my design

**Comment by amit-bhandari** [comment]
Okay sure

**Comment by jackingpanda** [comment]
@amit-bhandari you can't trust this guy, he just spamming all over the place with same "LOGO" proposal and then give you an icon from flaticon, claiming it was his logo he make.

**Comment by TacoTheDank** [comment]
@jackingpanda Whew, someone else who tells others about this fraud!

**Comment by amit-bhandari** [comment]
All right @jackingpanda , thanks for the heads up! 
Why would he do it anyway? Its not like I am gonna pay him or anything.

**Comment by TacoTheDank** [comment]
@amit-bhandari 

utopian.io will, with cryptocurrency :/

they're extremely against the sort of thing this guy's doing tho, so once I and some others reported him a few days ago, he was banned from their services

**Comment by amit-bhandari** [comment]
@TacoTheDank I see. Wonder how can people waste time doing such thing instead of doing something productive.

**Comment by TacoTheDank** [comment]
idek, he's also wasted time trying to slander me for calling him out lol
