### ISSUE TITLE
Adding friend's user name with special character crashes the app

### ISSUE THREAD

**Issue by neupanedipen** [amit-bhandari/AB-Remote-Wallpaper-Changer#5]
#### Expected behavior<br>
The app must be stable and should send the request to the friend having dot (•)in the username.<br>
#### Actual behavior<br>
But the app crashes when I try to send request to a friend&apos;s username having a dot (•).<br>
#### How to reproduce<br>
1. Install the app from playstore.<br>
2. Launch the app.<br>
3. Sign up for a new account if you don&apos;t have one. <br>
And sign into the app with your credentials.<br>
4. Now click on + icon on the friends tab and enter the user name to add as &quot;test.net&quot; without quotes. Or any username having dot (•)will cause the crash.<br>
The app crashes.<br>
* App Version: 1.0<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/8Z0v0pMAtWo

**Comment by amit-bhandari** [comment]
It has been solved in latest release in beta. 
Username with special characters are no more allowed to be created as firebase do not allow it.
