### ISSUE TITLE
Some profile details are hidden on screen rotation 

### ISSUE THREAD

**Issue by Olamatto** [amit-bhandari/AB-Remote-Wallpaper-Changer#6]
#### Expected behavior
The application is expected to work well on screen rotation of any kind, same way it work on portrait, it is expected to act the same way on landscape mode

#### Actual Behavior 
The application hides some profile details on landscape screen rotation, which can not be scrolled down to view. 

#### How to reproduce
- Download and install the application
- Lunch the application 
- Log in with your details or sign up
- Scroll to the profile tab after logging in
- Enable your screen rotation 
- Rotate to landscape mode

And profile details become missen, and cannot scroll down to access them. 

<hr>

Application version: 1.0
Operating system: Android v7.0

#### Recording Of The Bug
https://youtu.be/5ei6s45UGWU

**Comment by amit-bhandari** [comment]
It has been solved in development branch and currently in beta release
